/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * Machine d’état Connection (SECURITY-SPEC §15.1).
 */

export const CONNECTION_STATUSES = {
  PENDING_AUTH: "PENDING_AUTH",
  ACTIVE: "ACTIVE",
  DISABLED: "DISABLED",
  ERROR: "ERROR",
  ARCHIVED: "ARCHIVED",
} as const

export type ConnectionStatus =
  (typeof CONNECTION_STATUSES)[keyof typeof CONNECTION_STATUSES]

export const CONNECTION_STATUS_VALUES = [
  CONNECTION_STATUSES.PENDING_AUTH,
  CONNECTION_STATUSES.ACTIVE,
  CONNECTION_STATUSES.DISABLED,
  CONNECTION_STATUSES.ERROR,
  CONNECTION_STATUSES.ARCHIVED,
] as const satisfies readonly ConnectionStatus[]
