/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * Agrégat CredentialStatus (SECURITY-SPEC §15.2).
 */

export const CREDENTIAL_STATUSES = {
  MISSING: "MISSING",
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
  RETIRED: "RETIRED",
  FAILED: "FAILED",
} as const

export type CredentialStatus =
  (typeof CREDENTIAL_STATUSES)[keyof typeof CREDENTIAL_STATUSES]

export const CREDENTIAL_STATUS_VALUES = [
  CREDENTIAL_STATUSES.MISSING,
  CREDENTIAL_STATUSES.PENDING,
  CREDENTIAL_STATUSES.ACTIVE,
  CREDENTIAL_STATUSES.EXPIRED,
  CREDENTIAL_STATUSES.REVOKED,
  CREDENTIAL_STATUSES.RETIRED,
  CREDENTIAL_STATUSES.FAILED,
] as const satisfies readonly CredentialStatus[]
