/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * États InboundEnvelope (IMPL-PLAN §7.3).
 */

export const ENVELOPE_LIFECYCLE_STATUSES = {
  RECEIVED: "RECEIVED",
  NORMALIZED: "NORMALIZED",
  NORMALIZE_FAILED: "NORMALIZE_FAILED",
  ROUTED: "ROUTED",
  NO_MATCH: "NO_MATCH",
  AMBIGUOUS: "AMBIGUOUS",
  DISPATCHED: "DISPATCHED",
  DISCARDED: "DISCARDED",
  ARCHIVED: "ARCHIVED",
} as const

export type EnvelopeLifecycle =
  (typeof ENVELOPE_LIFECYCLE_STATUSES)[keyof typeof ENVELOPE_LIFECYCLE_STATUSES]

export const ENVELOPE_LIFECYCLE_VALUES = [
  ENVELOPE_LIFECYCLE_STATUSES.RECEIVED,
  ENVELOPE_LIFECYCLE_STATUSES.NORMALIZED,
  ENVELOPE_LIFECYCLE_STATUSES.NORMALIZE_FAILED,
  ENVELOPE_LIFECYCLE_STATUSES.ROUTED,
  ENVELOPE_LIFECYCLE_STATUSES.NO_MATCH,
  ENVELOPE_LIFECYCLE_STATUSES.AMBIGUOUS,
  ENVELOPE_LIFECYCLE_STATUSES.DISPATCHED,
  ENVELOPE_LIFECYCLE_STATUSES.DISCARDED,
  ENVELOPE_LIFECYCLE_STATUSES.ARCHIVED,
] as const satisfies readonly EnvelopeLifecycle[]
