/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * Capabilities Connector Registry V1 (IMPL-PLAN §20.2).
 */

export const INTEGRATION_CAPABILITIES = {
  POLL: "POLL",
  UPLOAD: "UPLOAD",
  CONTENT_FETCH: "CONTENT_FETCH",
  ARTIFACT_FETCH: "ARTIFACT_FETCH",
  DELTA_CURSOR: "DELTA_CURSOR",
  REPLAY_FROM_ENVELOPE: "REPLAY_FROM_ENVELOPE",
} as const

export type IntegrationCapability =
  (typeof INTEGRATION_CAPABILITIES)[keyof typeof INTEGRATION_CAPABILITIES]

export const INTEGRATION_CAPABILITY_VALUES = [
  INTEGRATION_CAPABILITIES.POLL,
  INTEGRATION_CAPABILITIES.UPLOAD,
  INTEGRATION_CAPABILITIES.CONTENT_FETCH,
  INTEGRATION_CAPABILITIES.ARTIFACT_FETCH,
  INTEGRATION_CAPABILITIES.DELTA_CURSOR,
  INTEGRATION_CAPABILITIES.REPLAY_FROM_ENVELOPE,
] as const satisfies readonly IntegrationCapability[]
