/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * Capacités contenu variante MESSAGE (SPEC §9.4).
 */

export const MESSAGE_CONTENT_CAPABILITIES = {
  CONTENT_FETCHABLE: "CONTENT_FETCHABLE",
  ATTACHMENTS_FETCHABLE: "ATTACHMENTS_FETCHABLE",
  CONTENT_INLINE: "CONTENT_INLINE",
} as const

export type MessageContentCapability =
  (typeof MESSAGE_CONTENT_CAPABILITIES)[keyof typeof MESSAGE_CONTENT_CAPABILITIES]

export const MESSAGE_CONTENT_CAPABILITY_VALUES = [
  MESSAGE_CONTENT_CAPABILITIES.CONTENT_FETCHABLE,
  MESSAGE_CONTENT_CAPABILITIES.ATTACHMENTS_FETCHABLE,
  MESSAGE_CONTENT_CAPABILITIES.CONTENT_INLINE,
] as const satisfies readonly MessageContentCapability[]
