/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * Outcomes Router (SPEC §16.1).
 */

export const ROUTING_OUTCOMES = {
  MATCH: "MATCH",
  NO_MATCH: "NO_MATCH",
  AMBIGUOUS_SOURCE: "AMBIGUOUS_SOURCE",
  DUPLICATE: "DUPLICATE",
  NO_ACTIVE_BINDING: "NO_ACTIVE_BINDING",
  ERROR: "ERROR",
} as const

export type RoutingOutcome = (typeof ROUTING_OUTCOMES)[keyof typeof ROUTING_OUTCOMES]

export const ROUTING_OUTCOME_VALUES = [
  ROUTING_OUTCOMES.MATCH,
  ROUTING_OUTCOMES.NO_MATCH,
  ROUTING_OUTCOMES.AMBIGUOUS_SOURCE,
  ROUTING_OUTCOMES.DUPLICATE,
  ROUTING_OUTCOMES.NO_ACTIVE_BINDING,
  ROUTING_OUTCOMES.ERROR,
] as const satisfies readonly RoutingOutcome[]
