/**
 * PLAN-INTEGRATION-PLATFORM-001 — LOT-1A
 * RuntimeHealth (SECURITY-SPEC §15.3).
 */

export const RUNTIME_HEALTH_STATUSES = {
  UNKNOWN: "UNKNOWN",
  HEALTHY: "HEALTHY",
  DEGRADED: "DEGRADED",
  UNHEALTHY: "UNHEALTHY",
} as const

export type RuntimeHealth =
  (typeof RUNTIME_HEALTH_STATUSES)[keyof typeof RUNTIME_HEALTH_STATUSES]

export const RUNTIME_HEALTH_VALUES = [
  RUNTIME_HEALTH_STATUSES.UNKNOWN,
  RUNTIME_HEALTH_STATUSES.HEALTHY,
  RUNTIME_HEALTH_STATUSES.DEGRADED,
  RUNTIME_HEALTH_STATUSES.UNHEALTHY,
] as const satisfies readonly RuntimeHealth[]
